language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t abhijithsj100/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true abhijithsj100/docker-react npm run test